export const WHITE_FANG_PLOT_SUMMARY = `
The story begins before the wolf-dog hybrid is born, with two men and their sled dog team on a journey to deliver the coffin of Lord Alfred to a remote town named Fort McGurry in the higher area of the Yukon Territory. The men, Bill and Henry, are stalked by a large pack of starving wolves over the course of several days. Finally, after all of their dogs and Bill have been eaten, more teams find Henry escaping from the wolves; the wolf pack scatters when they hear the large group of people coming.

The story then follows the pack, which has been robbed of its last prey. When the pack finally brings down a moose, the famine is ended; they eventually split up, and the story now follows a she-wolf and her mate, One Eye. One Eye claimed her after defeating and killing a younger rival. The she-wolf gives birth to a litter of five cubs by the Mackenzie River, and all but one die from hunger. One Eye is killed by a lynx while trying to rob her den for food for the she-wolf and her cub; his mate later discovers his remains near the lynx's den. The surviving cub and the she-wolf are left to fend for themselves. Shortly afterward, the she-wolf kills all the lynx's kittens to feed her cub, prompting the lynx to track her down, and a vicious fight breaks out. The she-wolf eventually kills the lynx but suffers severe injury; the lynx carcass is devoured over a period of seven days as the she-wolf recovers from her injuries.

One day, the cub comes across five indigenous people, and the she-wolf comes to his rescue. One man, Grey Beaver, recognizes the she-wolf as his brother's wolfdog, Kiche, who left during a famine. Grey Beaver's brother is dead, and so he takes Kiche and her cub and christens the cub "White Fang". White Fang has a harsh life in the native camp; the current puppy pack, seeing him as a wolf, immediately attacks him. The Indians save him, but the pups never accept him, and the leader, Lip-Lip, singles him out for persecution. White Fang grows to become a savage, callous, morose, solitary, and deadly fighter, "the enemy of his kind".

It is at this time that White Fang is separated from his mother, who is sold off to another Indian camp by Three Eagles. He realizes how hard life in the wild is when he runs away from camp, and earns the respect of Grey Beaver when he saves his son Mit-Sah from a group of boys seeking revenge. When a famine occurs, he runs away into the woods and encounters his mother Kiche, only for her to chase him away, for she has a new litter of cubs and has forgotten him. He also encounters Lip-Lip, whom he fights before returning to the camp.

When White Fang is five years old, he is taken to Fort Yukon, so that Grey Beaver can trade with the gold-hunters. There, when Grey Beaver is drunk, White Fang is bought by an evil dog-fighter named "Beauty" Smith. White Fang defeats all opponents pitted against him, including several wolves and a lynx, until a bulldog called Cherokee is brought in to fight him. Cherokee has the upper hand in the fight when he grips the skin and fur of White Fang's neck and begins to throttle him. White Fang nearly suffocates, but is rescued when a rich, young gold hunter, Weedon Scott, stops the fight, and forcefully buys White Fang from Beauty Smith.

Scott attempts to tame White Fang, and after a long, patient effort, he succeeds. When Scott attempts to return to California alone, White Fang pursues him, and Scott decides to take the dog with him back home. In Sierra Vista, White Fang must adjust to the laws of the estate. At the end of the book, an escaped convict, Jim Hall, tries to kill Scott's father, Judge Scott, for sentencing him to prison for a crime he did not commit, not knowing that Hall was "railroaded". White Fang kills Hall and is nearly killed himself, but survives. As a result, the women of Scott's estate name him "The Blessed Wolf". The story ends with White Fang relaxing in the sun with the puppies he has fathered with the sheep-dog Collie.`
